### ISSUE TITLE
Switch to higher version winapi (0.3.7?)

### ISSUE THREAD

**Issue by chandde** [yoshuawuyts/miow#23]
Is there plan to use newer version winapi? thanks! @alexcrichton

**Comment by alexcrichton** [comment]
Sorry I don't personally have time to maintain this crate any more, but if others are interested I don't mind transferring!

**Comment by quininer** [comment]
`miow` is an important part of the asynchronous ecosystem. Is anyone willing to maintain it? @carllerche @stjepang

**Comment by stjepang** [comment]
I believe @yoshuawuyts would be interested in maintaining it.

**Comment by yoshuawuyts** [comment]
Sure, I'd be happy to! @alexcrichton if you transfer it to me, I'd be happy to pick it up from there.

**Comment by alexcrichton** [comment]
Transferred over and invited to crates.io, thanks @yoshuawuyts!

**Comment by Veykril** [comment]
This issue no longer seems to be relevant as the crate moved on to using `windows` over `winapi`
