### ISSUE TITLE
cargo audit alert for net2 0.2.37

### ISSUE THREAD

**Issue by smhmayboudi** [yoshuawuyts/miow#43]
Hi, would you please check cargo audit. I receive a message regarding one of miow deps. and it would be nice to put the cargo audit in your build pipeline.
```bash
Crate:         net2
Version:       0.2.37
Warning:       unmaintained
Title:         `net2` crate has been deprecated; use `socket2` instead
Date:          2020-05-01
ID:            RUSTSEC-2020-0016
URL:           https://rustsec.org/advisories/RUSTSEC-2020-0016
```

**Comment by faern** [comment]
Latest `miow` does not use `net2`. `miow 0.3.x` uses `socket2` instead already. So this is not a problem in `miow`, but maybe you are stuck on older `miow` because of one of your dependencies. Ask that dependency to migrate to the newest `miow` instead please.
