### ISSUE TITLE
Add safe wrappers for overlapped I/O

### ISSUE THREAD

**Issue by notgull** [yoshuawuyts/miow#60]
I'm not sure entirely what the scope of this crate is (it seems to be mostly limited to unsafe bindings to the Windows API), but would it be a welcome addition to add a safe way of doing overlapped operations?

**Comment by faern** [comment]
This crate is pretty dead. I would not depend on any new functionality being added unless a new dedicated maintainer takes over :)

**Comment by notgull** [comment]
Okay. I'm not willing to take over this crate, so I guess I'll close this issue for now.
